# Generated by Django 4.0.2 on 2023-06-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_seller_alter_classifieds_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='classifieds',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='login.seller'),
        ),
    ]
