# Generated by Django 4.0.2 on 2023-06-24 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_rename_user_seller_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieds',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
