# Generated by Django 4.0.2 on 2023-06-24 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_classifieds_updated_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifieds',
            new_name='Classifields',
        ),
    ]
