# Generated by Django 4.0.2 on 2023-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_classifields_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='classifieds',
            field=models.ManyToManyField(blank=True, related_name='tags', to='login.Classifields'),
        ),
    ]
