# Generated by Django 4.0.2 on 2023-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_tag_classifieds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='classifieds',
        ),
        migrations.AddField(
            model_name='classifields',
            name='tag',
            field=models.ManyToManyField(blank=True, to='login.Tag'),
        ),
    ]
