# Generated by Django 4.0.2 on 2023-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_tag_classifieds_classifields_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifields',
            name='tag',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tag', models.ManyToManyField(blank=True, to='login.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='classifields',
            name='category',
            field=models.ManyToManyField(blank=True, to='login.Category'),
        ),
    ]
