# Generated by Django 4.0.2 on 2023-07-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_classifields_tag_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.category'),
        ),
    ]
