# Generated by Django 4.0.2 on 2023-07-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_category_tag_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifields',
            name='tag',
            field=models.ManyToManyField(blank=True, to='login.Tag'),
        ),
    ]
