# Generated by Django 4.0.2 on 2023-07-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_classifields_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifields',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
