# Generated by Django 4.0.2 on 2023-07-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_category_category_name_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifields',
            old_name='subCategory',
            new_name='subcategory',
        ),
    ]
