# Generated by Django 4.2.3 on 2023-07-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_location_classifields_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifields',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
